version: '3.7'

networks:
  test:
    driver: bridge

services:
  api_tests:
    container_name: api_tests
    build:
      context: .
      dockerfile: ./Dockerfile.go.test
    environment:
      - MONGO_URI=mongodb://mongo_test:27017
      - MONGO_NAME=discovery
      - ADS_URL=https://coding-challenge.dsc.tv/v1/ads/
      - DOCKER_TEST=true
    depends_on:
      - mongo_test
    networks:
      - test
  mongo_test:
    container_name: mongo_test
    build:
      context: ./mongo
      dockerfile: Dockerfile.test
    environment:
      - MONGO_INITDB_DATABASE=discovery
    volumes:
      - db_data:/data/db
    logging:
      driver: none
    ports:
      - "5002:27017"
    expose:
     - "27017"
    restart: on-failure
    networks:
      - test
#  mongo-seed:
#    container_name: mongo-seed
#    build:
#      context: ./mongo-seed
#      dockerfile: Dockerfile.test
#    links:
#      - mongo_test
#    networks:
#      - test

volumes:
  db_data:
    name: mongo_data
